server:
  port: 9095
spring:
  application:
    name: spring-cloud-config-bus-clientt
  rabbitmq:
    host: 192.168.67.133
  cloud:
    bus:
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always