server:
  port: 5555
spring:
  application:
    name: spring-cloud-change-param-zuul-server
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    spring-cloud-change-param-provider:
      path: /provider/**
      serviceId: spring-cloud-change-param-provider
  retryable: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 1 # \u5BF9\u7B2C\u4E00\u6B21\u8BF7\u6C42\u7684\u670D\u52A1\u7684\u91CD\u8BD5\u6B21\u6570
  MaxAutoRetriesNextServer: 1 # \u8981\u91CD\u8BD5\u7684\u4E0B\u4E00\u4E2A\u670D\u52A1\u7684\u6700\u5927\u6570\u91CF\uFF08\u4E0D\u5305\u62EC\u7B2C\u4E00\u4E2A\u670D\u52A1\uFF09
  OkToRetryOnAllOperations: true
  okhttp:
    enabled: true
  http:
    client:
      enabled: false
