spring:
  application:
    # \u670D\u52A1\u540D\u79F0
    name: eureka-server
server:
  # \u670D\u52A1\u7AEF\u53E3
  port: 8761

eureka:
  instance:
    # host name
    hostname: localhost
  client:
    # \u662F\u5426\u83B7\u53D6\u6CE8\u518C\u8868
    fetch-registry: false
    service-url:
      # \u9ED8\u8BA4 Zone
      defaultZone: http://${spring.application.name:localhost}:${server.port:8761}/eureka/
    # \u662F\u5426\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
  server:
    # \u662F\u5426\u5F00\u542F\u81EA\u6211\u4FDD\u62A4
    enable-self-preservation: false
