spring:
  application:
    name: eureka-server # 服务名称
server:
  port: 8761 # 服务端口

eureka:
  instance:
    hostname: localhost # host name
  client:
    fetch-registry: false # 是否获取注册表
    service-url:
      defaultZone: http://localhost:${server.port:8761}/eureka/ # 默认 Zone
    register-with-eureka: false # 是否注册自己
  server:
    enable-self-preservation: true # 是否开启自我保护，默认 true。在本机测试可以使用 false，但是在生产环境下必须为 true