spring:
  application:
    name: spring-cloud-eureka-client-simple # 工程名称，也是注册到 server 后的实例名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      # 指定 Zone，需要与 Eureka Server 一样
  instance:
    prefer-ip-address: true # 使用 ip 注册，默认为 false。为 false 时是 机器名
    instance-id: ${spring.application.name}:${server.port} # 注册到 server 后显示的名字，默认是 机器名:name:端口

server:
  port: 8081 # 端口