server:
  port: 8081

spring:
  application:
    name: spring-cloud-eureka-client-https

eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: client.p12
      key-store-password: 654321
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/