server:
  port: 8081
spring:
  application:
    name: spring-cloud-eureka-client-region-zone
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    region: region-east
    availability-zones:
      region-east: zone1,zone2
    service-url:
      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/