spring:
  application:
    name: spring-cloud-eureka-server-ha
server:
  port: 8764

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    hostname: peer3
