server:
  port: 5555
spring:
  application:
    name: spring-cloud-ratelimit-zuul-server
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    spring-cloud-ratelimit-provider-service:
      path: /provider/**
      serviceId: spring-cloud-ratelimit-provider-service
  ratelimit:
    key-prefix: springcloud # \u6309\u7C92\u5EA6\u62C6\u5206\u7684\u4E34\u65F6\u53D8\u91CF key \u7684\u524D\u7F00
    enabled: true # \u542F\u7528\u5F00\u5173
    repository: in_memory # key \u7684\u5B58\u50A8\u7C7B\u578B\uFF0C\u9ED8\u8BA4\u662F in_memory
    behind-proxy: true # \u8868\u793A\u4EE3\u7406\u4E4B\u540E
    default-policy:
      limit: 2 # \u5728\u4E00\u4E2A\u5355\u4F4D\u65F6\u95F4\u5185\u7684\u8BF7\u6C42\u6570\u91CF
      quota: 1 # \u5728\u4E00\u4E2A\u5355\u4F4D\u65F6\u95F4\u5185\u7684\u8BF7\u6C42\u65F6\u95F4\u9650\u5236
      refresh-interval: 3 # \u5355\u4F4D\u65F6\u95F4\u7A97\u53E3
      type:
        - user # \u53EF\u6307\u5B9A\u7528\u6237\u7C92\u5EA6
        - origin # \u53EF\u6307\u5B9A\u5BA2\u6237\u7AEF\u5730\u5740\u7C92\u5EA6
        - url # \u53EF\u6307\u5B9A url \u7C92\u5EA6