spring:
  application:
    name: spring-cloud-zuul-security-auth-server
server:
  port: 7777
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/