spring:
  application:
    name: spring-cloud-zuul-simple
server:
  port: 8989
#  undertow:
#    io-threads: 10
#    worker-threads: 10
#    direct-buffers: true
#    buffer-size: 1024 # 字节数
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-provider-service-simple:
      path: /provider/**
      serviceId: spring-cloud-provider-service-simple

