spring:
  application:
    name: spring-cloud-zuul-simple
server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-provider-service-simple-a:
      path: /provider/**
      serviceId: spring-cloud-provider-service-simple-a
    spring-cloud-provider-service-simple-b:
      path: /provider/**
      serviceId: spring-cloud-provider-service-simple-b
