server:
  port: 8761
spring:
  security:
    user:
      name: laiyy
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port:8761}/eureka/
    register-with-eureka: false
    fetch-registry: false
