server:
  port: 9999
spring:
  application:
    name: spring-cloud-hystrix-cache-provider-user

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
