server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway-simple-1
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://baidu.com
          predicates:
            - Path=/baidu


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.nettu: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'