server:
  port: 9091
spring:
  application:
    name: spring-cloud-autoconfig-client
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always