server:
  port: 9090
spring:
  application:
    name: spring-cloud-autoconfig-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/laiyy0728/config-repo
          search-paths: config-simple