spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/laiyy0728/config-repo
          search-paths: config-simple
  application:
    name: spring-cloud-config-simple-server
server:
  port: 9090