server:
  port: 7070
spring:
  application:
    name: spring-cloud-change-param-provider
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/