spring:
  application:
    name: spring-cloud-eureka-server-region-zone
server:
  port: 8763

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
    region: region-east # 设置 region
    availability-zones:
      region-east: zone1,zone2 # 设置可用 region-zone
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      zone: zone2 # 设置 zone
